#!/usr/bin/env bash

## Make sure to have root privilege
if [ "$(whoami)" != 'root' ]; then
  echo -e "\e[31m\xe2\x9d\x8c Please retry with root privilege.\e[m"
  exit 1
fi

## Remove extra files generated by NVIDIA driver
echo -e "\e[33m\xe2\x8f\xb3 Remove extra files generated by NVIDIA driver ...\e[m"
[ -d /opt/nvidia ] && rm -rfv /opt/nvidia
[ -d /usr/src/nvidia* ] && rm -rfv /usr/src/nvidia*
for i in /usr/bin/nvidia-modprobe /usr/lib/libGL.so.1; do
  [ -f $i ] && rm -fv $i
done
ldconfig

echo -e "\e[32m\xf0\x9f\x91\x8f Cleaning completed!\e[m"
